# Generated by Django 5.1.6 on 2025-02-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geocoder", "0002_alter_addresscoordinates_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addresscoordinates",
            name="address",
            field=models.TextField(max_length=200, verbose_name="Адрес места"),
        ),
        migrations.AlterField(
            model_name="addresscoordinates",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Широта"),
        ),
        migrations.AlterField(
            model_name="addresscoordinates",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Долгота"),
        ),
        migrations.AlterField(
            model_name="addresscoordinates",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Дата/время обновления",
            ),
        ),
    ]
