# Generated by Django 5.1.6 on 2025-02-16 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_product_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(
                max_digits=8,
                decimal_places=2,
                default=0.0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Цена',
                help_text='Введите цену товара.',
            ),
        ),
    ]
