# Generated by Django 5.1.6 on 2025-02-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_alter_order_total_price_alter_orderitem_fixed_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('restaurant', 'Передан в ресторан'), ('delivery', 'У курьера'), ('completed', 'Завершён')], db_index=True, default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
