# Generated by Django 5.1.6 on 2025-02-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_order_called_at_order_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('electronic', 'Электронно'), ('cash', 'Наличные')], db_index=True, default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
