# Generated by Django 5.1.6 on 2025-02-20 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0051_remove_order_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="payment_method",
            field=models.CharField(
                choices=[("electronic", "Электронно"), ("cash", "Наличные")],
                db_index=True,
                default="cash",
                max_length=20,
                verbose_name="Способ оплаты",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="foodcartapp.restaurant",
            ),
        ),
    ]
