# Generated by Django 5.1.6 on 2025-02-24 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0054_alter_orderitem_fixed_price_alter_orderitem_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="price",
        ),
    ]
